/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_jni_HALUtil */

#ifndef _Included_io_github_robolib_jni_HALUtil
#define _Included_io_github_robolib_jni_HALUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_robolib_jni_HALUtil_NULL_PARAMETER
#define io_github_robolib_jni_HALUtil_NULL_PARAMETER -1005L
#undef io_github_robolib_jni_HALUtil_SAMPLE_RATE_TOO_HIGH
#define io_github_robolib_jni_HALUtil_SAMPLE_RATE_TOO_HIGH 1001L
#undef io_github_robolib_jni_HALUtil_VOLTAGE_OUT_OF_RANGE
#define io_github_robolib_jni_HALUtil_VOLTAGE_OUT_OF_RANGE 1002L
#undef io_github_robolib_jni_HALUtil_LOOP_TIMING_ERROR
#define io_github_robolib_jni_HALUtil_LOOP_TIMING_ERROR 1004L
#undef io_github_robolib_jni_HALUtil_INCOMPATIBLE_STATE
#define io_github_robolib_jni_HALUtil_INCOMPATIBLE_STATE 1015L
#undef io_github_robolib_jni_HALUtil_ANALOG_TRIGGER_PULSE_OUTPUT_ERROR
#define io_github_robolib_jni_HALUtil_ANALOG_TRIGGER_PULSE_OUTPUT_ERROR -1011L
#undef io_github_robolib_jni_HALUtil_NO_AVAILABLE_RESOURCES
#define io_github_robolib_jni_HALUtil_NO_AVAILABLE_RESOURCES -104L
#undef io_github_robolib_jni_HALUtil_PARAMETER_OUT_OF_RANGE
#define io_github_robolib_jni_HALUtil_PARAMETER_OUT_OF_RANGE -1028L
/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    initializeMutexNormal
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_jni_HALUtil_initializeMutexNormal
  (JNIEnv *, jclass);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    deleteMutex
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_HALUtil_deleteMutex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    takeMutex
 * Signature: (Ljava/nio/ByteBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_jni_HALUtil_takeMutex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    initializeMultiWait
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_jni_HALUtil_initializeMultiWait
  (JNIEnv *, jclass);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    deleteMultiWait
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_HALUtil_deleteMultiWait
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    takeMultiWait
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_jni_HALUtil_takeMultiWait
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getFPGAVersion
 * Signature: (Ljava/nio/IntBuffer;)S
 */
JNIEXPORT jshort JNICALL Java_io_github_robolib_jni_HALUtil_getFPGAVersion
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getFPGARevision
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_HALUtil_getFPGARevision
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getFPGATime
 * Signature: (Ljava/nio/IntBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_robolib_jni_HALUtil_getFPGATime
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getFPGAButton
 * Signature: (Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_robolib_jni_HALUtil_getFPGAButton
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getHALErrorMessage
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_robolib_jni_HALUtil_getHALErrorMessage
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getHALErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_HALUtil_getHALErrno
  (JNIEnv *, jclass);

/*
 * Class:     io_github_robolib_jni_HALUtil
 * Method:    getHALstrerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_robolib_jni_HALUtil_getHALstrerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
