/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_DIOJNI */

#ifndef _Included_io_github_robolib_hal_DIOJNI
#define _Included_io_github_robolib_hal_DIOJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    initializeDigitalPort
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_hal_DIOJNI_initializeDigitalPort
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    allocateDIO
 * Signature: (Ljava/nio/ByteBuffer;BLjava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_DIOJNI_allocateDIO
  (JNIEnv *, jclass, jobject, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    freeDIO
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_DIOJNI_freeDIO
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    setDIO
 * Signature: (Ljava/nio/ByteBuffer;SLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_DIOJNI_setDIO
  (JNIEnv *, jclass, jobject, jshort, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    getDIO
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_DIOJNI_getDIO
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    getDIODirection
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_DIOJNI_getDIODirection
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    pulse
 * Signature: (Ljava/nio/ByteBuffer;DLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_DIOJNI_pulse
  (JNIEnv *, jclass, jobject, jdouble, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    isPulsing
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_DIOJNI_isPulsing
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    isAnyPulsing
 * Signature: (Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_DIOJNI_isAnyPulsing
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_hal_DIOJNI
 * Method:    getLoopTiming
 * Signature: (Ljava/nio/IntBuffer;)S
 */
JNIEXPORT jshort JNICALL Java_io_github_robolib_hal_DIOJNI_getLoopTiming
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
