/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_JNIWrapper */

#ifndef _Included_io_github_robolib_hal_JNIWrapper
#define _Included_io_github_robolib_hal_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_JNIWrapper
 * Method:    getPortWithModule
 * Signature: (BB)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_hal_JNIWrapper_getPortWithModule
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     io_github_robolib_hal_JNIWrapper
 * Method:    getPort
 * Signature: (B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_hal_JNIWrapper_getPort
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
