/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_jni_PowerJNI */

#ifndef _Included_io_github_robolib_jni_PowerJNI
#define _Included_io_github_robolib_jni_PowerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getVinVoltage
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getVinVoltage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getVinCurrent
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getVinCurrent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserVoltage6V
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getUserVoltage6V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserCurrent6V
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getUserCurrent6V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserActive6V
 * Signature: (Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_robolib_jni_PowerJNI_getUserActive6V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserCurrentFaults6V
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_PowerJNI_getUserCurrentFaults6V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserVoltage5V
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getUserVoltage5V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserCurrent5V
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getUserCurrent5V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserActive5V
 * Signature: (Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_robolib_jni_PowerJNI_getUserActive5V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserCurrentFaults5V
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_PowerJNI_getUserCurrentFaults5V
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserVoltage3V3
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getUserVoltage3V3
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserCurrent3V3
 * Signature: (Ljava/nio/IntBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_robolib_jni_PowerJNI_getUserCurrent3V3
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserActive3V3
 * Signature: (Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_robolib_jni_PowerJNI_getUserActive3V3
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_jni_PowerJNI
 * Method:    getUserCurrentFaults3V3
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_PowerJNI_getUserCurrentFaults3V3
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
