/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_CounterJNI */

#ifndef _Included_io_github_robolib_hal_CounterJNI
#define _Included_io_github_robolib_hal_CounterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    initializeCounter
 * Signature: (ILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_hal_CounterJNI_initializeCounter
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    freeCounter
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_freeCounter
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterAverageSize
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterAverageSize
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterUpSource
 * Signature: (Ljava/nio/ByteBuffer;IBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterUpSource
  (JNIEnv *, jclass, jobject, jint, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterUpSourceEdge
 * Signature: (Ljava/nio/ByteBuffer;BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterUpSourceEdge
  (JNIEnv *, jclass, jobject, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    clearCounterUpSource
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_clearCounterUpSource
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterDownSource
 * Signature: (Ljava/nio/ByteBuffer;IBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterDownSource
  (JNIEnv *, jclass, jobject, jint, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterDownSourceEdge
 * Signature: (Ljava/nio/ByteBuffer;BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterDownSourceEdge
  (JNIEnv *, jclass, jobject, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    clearCounterDownSource
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_clearCounterDownSource
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterUpDownMode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterUpDownMode
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterExternalDirectionMode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterExternalDirectionMode
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterSemiPeriodMode
 * Signature: (Ljava/nio/ByteBuffer;BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterSemiPeriodMode
  (JNIEnv *, jclass, jobject, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterPulseLengthMode
 * Signature: (Ljava/nio/ByteBuffer;DLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterPulseLengthMode
  (JNIEnv *, jclass, jobject, jdouble, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    getCounterSamplesToAverage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_CounterJNI_getCounterSamplesToAverage
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterSamplesToAverage
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterSamplesToAverage
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    resetCounter
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_resetCounter
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    getCounter
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_CounterJNI_getCounter
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    getCounterPeriod
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_robolib_hal_CounterJNI_getCounterPeriod
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterMaxPeriod
 * Signature: (Ljava/nio/ByteBuffer;DLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterMaxPeriod
  (JNIEnv *, jclass, jobject, jdouble, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterUpdateWhenEmpty
 * Signature: (Ljava/nio/ByteBuffer;BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterUpdateWhenEmpty
  (JNIEnv *, jclass, jobject, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    getCounterStopped
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_CounterJNI_getCounterStopped
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    getCounterDirection
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_CounterJNI_getCounterDirection
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_CounterJNI
 * Method:    setCounterReverseDirection
 * Signature: (Ljava/nio/ByteBuffer;BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_CounterJNI_setCounterReverseDirection
  (JNIEnv *, jclass, jobject, jbyte, jobject);

#ifdef __cplusplus
}
#endif
#endif
