/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_EncoderJNI */

#ifndef _Included_io_github_robolib_hal_EncoderJNI
#define _Included_io_github_robolib_hal_EncoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    initializeEncoder
 * Signature: (BIBBIBBLjava/nio/IntBuffer;Ljava/nio/IntBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_hal_EncoderJNI_initializeEncoder
  (JNIEnv *, jclass, jbyte, jint, jbyte, jbyte, jint, jbyte, jbyte, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    freeEncoder
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_EncoderJNI_freeEncoder
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    resetEncoder
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_EncoderJNI_resetEncoder
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    getEncoder
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_EncoderJNI_getEncoder
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    getEncoderPeriod
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_robolib_hal_EncoderJNI_getEncoderPeriod
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    setEncoderMaxPeriod
 * Signature: (Ljava/nio/ByteBuffer;DLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_EncoderJNI_setEncoderMaxPeriod
  (JNIEnv *, jclass, jobject, jdouble, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    getEncoderStopped
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_EncoderJNI_getEncoderStopped
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    getEncoderDirection
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_EncoderJNI_getEncoderDirection
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    setEncoderReverseDirection
 * Signature: (Ljava/nio/ByteBuffer;BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_EncoderJNI_setEncoderReverseDirection
  (JNIEnv *, jclass, jobject, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    setEncoderSamplesToAverage
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_EncoderJNI_setEncoderSamplesToAverage
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    getEncoderSamplesToAverage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_EncoderJNI_getEncoderSamplesToAverage
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_EncoderJNI
 * Method:    setEncoderIndexSource
 * Signature: (Ljava/nio/ByteBuffer;IZZZLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_EncoderJNI_setEncoderIndexSource
  (JNIEnv *, jclass, jobject, jint, jboolean, jboolean, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
