/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_I2CJNI */

#ifndef _Included_io_github_robolib_hal_I2CJNI
#define _Included_io_github_robolib_hal_I2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_I2CJNI
 * Method:    i2CInitialize
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_I2CJNI_i2CInitialize
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_I2CJNI
 * Method:    i2CTransaction
 * Signature: (BBLjava/nio/ByteBuffer;BLjava/nio/ByteBuffer;B)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_I2CJNI_i2CTransaction
  (JNIEnv *, jclass, jbyte, jbyte, jobject, jbyte, jobject, jbyte);

/*
 * Class:     io_github_robolib_hal_I2CJNI
 * Method:    i2CWrite
 * Signature: (BBLjava/nio/ByteBuffer;B)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_I2CJNI_i2CWrite
  (JNIEnv *, jclass, jbyte, jbyte, jobject, jbyte);

/*
 * Class:     io_github_robolib_hal_I2CJNI
 * Method:    i2CRead
 * Signature: (BBLjava/nio/ByteBuffer;B)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_robolib_hal_I2CJNI_i2CRead
  (JNIEnv *, jclass, jbyte, jbyte, jobject, jbyte);

/*
 * Class:     io_github_robolib_hal_I2CJNI
 * Method:    i2CClose
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_I2CJNI_i2CClose
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
