/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_jni_SPIJNI */

#ifndef _Included_io_github_robolib_jni_SPIJNI
#define _Included_io_github_robolib_jni_SPIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiInitialize
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiInitialize
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiTransaction
 * Signature: (BLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;B)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_SPIJNI_spiTransaction
  (JNIEnv *, jclass, jbyte, jobject, jobject, jbyte);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiWrite
 * Signature: (BLjava/nio/ByteBuffer;B)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_SPIJNI_spiWrite
  (JNIEnv *, jclass, jbyte, jobject, jbyte);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiRead
 * Signature: (BLjava/nio/ByteBuffer;B)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_jni_SPIJNI_spiRead
  (JNIEnv *, jclass, jbyte, jobject, jbyte);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiClose
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiClose
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiSetSpeed
 * Signature: (BI)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiSetSpeed
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiSetBitsPerWord
 * Signature: (BB)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiSetBitsPerWord
  (JNIEnv *, jclass, jbyte, jbyte);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiSetOpts
 * Signature: (BIII)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiSetOpts
  (JNIEnv *, jclass, jbyte, jint, jint, jint);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiSetChipSelectActiveHigh
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiSetChipSelectActiveHigh
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_jni_SPIJNI
 * Method:    spiSetChipSelectActiveLow
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_jni_SPIJNI_spiSetChipSelectActiveLow
  (JNIEnv *, jclass, jbyte, jobject);

#ifdef __cplusplus
}
#endif
#endif
