/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_SerialPortJNI */

#ifndef _Included_io_github_robolib_hal_SerialPortJNI
#define _Included_io_github_robolib_hal_SerialPortJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialInitializePort
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialInitializePort
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetBaudRate
 * Signature: (BILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetBaudRate
  (JNIEnv *, jclass, jbyte, jint, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetDataBits
 * Signature: (BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetDataBits
  (JNIEnv *, jclass, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetParity
 * Signature: (BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetParity
  (JNIEnv *, jclass, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetStopBits
 * Signature: (BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetStopBits
  (JNIEnv *, jclass, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetWriteMode
 * Signature: (BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetWriteMode
  (JNIEnv *, jclass, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetFlowControl
 * Signature: (BBLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetFlowControl
  (JNIEnv *, jclass, jbyte, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetTimeout
 * Signature: (BFLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetTimeout
  (JNIEnv *, jclass, jbyte, jfloat, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialEnableTermination
 * Signature: (BCLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialEnableTermination
  (JNIEnv *, jclass, jbyte, jchar, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialDisableTermination
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialDisableTermination
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetReadBufferSize
 * Signature: (BILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetReadBufferSize
  (JNIEnv *, jclass, jbyte, jint, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialSetWriteBufferSize
 * Signature: (BILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialSetWriteBufferSize
  (JNIEnv *, jclass, jbyte, jint, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialGetBytesRecieved
 * Signature: (BLjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialGetBytesRecieved
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialRead
 * Signature: (BLjava/nio/ByteBuffer;ILjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialRead
  (JNIEnv *, jclass, jbyte, jobject, jint, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialWrite
 * Signature: (BLjava/nio/ByteBuffer;ILjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialWrite
  (JNIEnv *, jclass, jbyte, jobject, jint, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialFlush
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialFlush
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialClear
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialClear
  (JNIEnv *, jclass, jbyte, jobject);

/*
 * Class:     io_github_robolib_hal_SerialPortJNI
 * Method:    serialClose
 * Signature: (BLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_SerialPortJNI_serialClose
  (JNIEnv *, jclass, jbyte, jobject);

#ifdef __cplusplus
}
#endif
#endif
