/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_PWMJNI */

#ifndef _Included_io_github_robolib_hal_PWMJNI
#define _Included_io_github_robolib_hal_PWMJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    allocatePWMChannel
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_robolib_hal_PWMJNI_allocatePWMChannel
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    freePWMChannel
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_freePWMChannel
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    setPWM
 * Signature: (Ljava/nio/ByteBuffer;SLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_setPWM
  (JNIEnv *, jclass, jobject, jshort, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    getPWM
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)S
 */
JNIEXPORT jshort JNICALL Java_io_github_robolib_hal_PWMJNI_getPWM
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    latchPWMZero
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_latchPWMZero
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    setPWMPeriodScale
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_setPWMPeriodScale
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    allocatePWM
 * Signature: (Ljava/nio/IntBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_robolib_hal_PWMJNI_allocatePWM
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    freePWM
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_freePWM
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    setPWMRate
 * Signature: (DLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_setPWMRate
  (JNIEnv *, jclass, jdouble, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    setPWMDutyCycle
 * Signature: (Ljava/nio/ByteBuffer;DLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_setPWMDutyCycle
  (JNIEnv *, jclass, jobject, jdouble, jobject);

/*
 * Class:     io_github_robolib_hal_PWMJNI
 * Method:    setPWMOutputChannel
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_robolib_hal_PWMJNI_setPWMOutputChannel
  (JNIEnv *, jclass, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
