/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_robolib_hal_InterruptJNI_InterruptJNIHandlerFunction */

#ifndef _Included_io_github_robolib_hal_InterruptJNI_InterruptJNIHandlerFunction
#define _Included_io_github_robolib_hal_InterruptJNI_InterruptJNIHandlerFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
